language: php

php:
  - 7

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

# We need nodejs version >= 4 to be compatible with htmlhint >= 0.9.13
before_install:
  - nvm install node

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - npm install htmlhint -g

script:
  - php build.php -e=prod
  - htmlhint _site

#after_success:
#  - bash deploy.sh
#  - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/${Cloudflare_zone}/purge_cache\" \
#    -H \"X-Auth-Email: arnaud@ligny.org\" \
#    -H \"X-Auth-Key: ${Cloudflare_API}\" \
#    -H \"Content-Type: application/json\" \
#    --data '{\"purge_everything\":true}'"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
