language: php

php:
  - 5.6

install:
  - composer self-update

before_script:
  - composer install --no-interaction

script:
  - php build.php -e=prod

deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: master
