sudo: false
language: php
php:
  - 7

env:
  global:
    - SCRIPT_BUILD="scripts/build.php"
    - SCRIPT_DEPLOY="scripts/deploy/ghpages.sh"
    - SCRIPT_CACHE="scripts/deploy/cloudflare.sh"
    - REPO=$TRAVIS_REPO_SLUG
    - SOURCE_BRANCH=$TRAVIS_BRANCH
    - TARGET_BRANCH="gh-pages"
    - SITE_DIR="_site"

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
    - "$HOME/.nvm"

# we need NodeJS version >= 4
# to be compatible with htmlhint >= 0.9.13
before_install:
  - nvm install node

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - npm install htmlhint -g

script:
  # build site
  - php $SCRIPT_BUILD -e=prod
  # analyse HTML
  - htmlhint $SITE_DIR

deploy:
  # deploy to GH Pages with a script
#  - provider: script
#    skip_cleanup: true
#    script: "sh $TRAVIS_BUILD_DIR/$SCRIPT_DEPLOY"
#    on:
#      branch: $SOURCE_BRANCH
  # deploy to GH Pages
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: $SITE_DIR
    target_branch: $TARGET_BRANCH
    email: contact@travis-ci.org
    name: "Travis bot"
    on:
      branch: $SOURCE_BRANCH

# purge cache
after_deploy:
  - sh $SCRIPT_CACHE
