sudo: false
language: php
php:
  - 7

env:
  global:
    - REPO=$TRAVIS_REPO_SLUG
    - SOURCE_BRANCH=$TRAVIS_BRANCH
    - TARGET_BRANCH="gh-pages"
    - SITE_DIR="_site"

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
    - "$HOME/.nvm"

# We need nodejs version >= 4 to be compatible with htmlhint >= 0.9.13
before_install:
  - nvm install node

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - npm install htmlhint -g

script:
  - php build.php -e=prod
  - htmlhint $SITE_DIR

deploy:
  - provider: script
    skip_cleanup: true
    script: "sh $TRAVIS_BUILD_DIR/deploy.sh && sh $TRAVIS_BUILD_DIR/cloudflare.sh"
    on:
      branch: $SOURCE_BRANCH
