title: Arnaud Ligny
baseline: Consultant technique Web, mobile & e-commerce
baseurl: https://arnaudligny.fr/
description: Arnaud Ligny, Consultant technique Web, mobile & e-commerce.
keywords:
- Consultant technique
- Web
- Application Mobile
- e-commerce
- Magento
- IoT
menus:
  main:
    - id: blog
      weight: 1
    - id: projets
      weight: 2
  footer:
    - id: a-propos
      name: À propos
      url: a-propos
author:
  firstname: Arnaud
  lastname: Ligny
  email: arnaud[AROBASE]ligny[POINT]fr
  username: Narno
  job: Consultant technique
  cv: CV_ArnaudLigny-2016.pdf
  statut: En poste
social:
  twitter: ArnaudLigny
  github: Narno
  linkedin: arnaudligny
  facebook_id: 516589570
language: fr
languages:
  - code: fr
    name: Français
    locale: fr_FR
output:
  formats:
    netlify_redirects:
      mediatype: text/plain
      extension: ''
    webmanifest:
      mediatype: application/manifest+json
      extension: webmanifest
  pagetypeformats:
    section: ['html', 'atom', 'rss', 'json']
virtualpages:
  manifest:
    output: webmanifest
  /code:
    redirect: https://github.com/Narno
  /blog/work-in-progress:
    redirect: /
  /blog/v-rifier-la-validit-des-fichiers-de-configuration-xml-de-magento:
    redirect: blog/verifier-la-validite-des-fichiers-de-configuration-xml-de-magento/
  /blog/t-l-charger-manuellement-une-extension-magento:
    redirect: blog/telecharger-manuellement-une-extension-magento/
  _redirects:
    output: netlify_redirects
googleanalytics: UA-30599234-2
source: https://github.com/Narno/arnaudligny.fr/edit/master/content/
comments: false
static:
  exclude:
  - CV_ArnaudLigny-2014.pdf
  - CV_ArnaudLigny-2015.pdf
editor: typora
theme: garth
logo: aligny.jpg
image: aligny.jpg
