title: Arnaud Ligny
baseline: Consultant technique web, mobile & e-commerce
baseurl: https://arnaudligny.fr/
description: Arnaud Ligny, Consultant technique web, mobile & e-commerce.
keywords:
  - Consultant technique
  - Web
  - Application Mobile
  - e-commerce
  - Magento
  - IoT
language: fr
languages:
  - code: fr
    name: Français
    locale: fr_FR
menus:
  main:
    - id: index
      name: Accueil
      weight: 0
    - id: cv
      name: CV
      weight: 1
    - id: blog
      weight: 2
    - id: projets
      weight: 3
  footer:
    - id: a-propos
      name: À propos
      url: a-propos
author:
  firstname: Arnaud
  lastname: Ligny
  url: https://arnaudligny.fr
  email: arnaud[AROBASE]ligny[POINT]fr
  job: Consultant technique
  cv: CV_ArnaudLigny-2016.pdf
  statut: En poste
social:
  twitter:
    site: ArnaudLigny
    creator: ArnaudLigny
    url: https://twitter.com/ArnaudLigny
  github:
    username: ArnaudLigny
    url: https://github.com/ArnaudLigny
  linkedin:
    username: arnaudligny
    url: https://fr.linkedin.com/in/arnaudligny/fr/
output:
  formats:
    - name: elasticlunr
      mediatype: 'application/json'
      filename: 'elasticlunr'
      extension: 'json'
  pagetypeformats:
    homepage: ['html', 'atom', 'elasticlunr']
    section: ['html', 'atom', 'json']
defaultpages:
  sitemap:
    published: true
  404:
    published: true
virtualpages:
  # short URL / redirects
  - path: code
    redirect: https://github.com/ArnaudLigny
  - path: tw
    redirect: https://twitter.com/ArnaudLigny
  # old URL
  - path: blog/work-in-progress
    redirect: /
  - path: blog/v-rifier-la-validit-des-fichiers-de-configuration-xml-de-magento
    redirect: blog/verifier-la-validite-des-fichiers-de-configuration-xml-de-magento/
  - path: blog/t-l-charger-manuellement-une-extension-magento
    redirect: blog/telecharger-manuellement-une-extension-magento/
source: https://github.com/ArnaudLigny/arnaudligny.fr/edit/master/content/
comments: false
static:
  exclude:
    - CV_ArnaudLigny-2014.pdf
    - CV_ArnaudLigny-2015.pdf
    - _bck
    - gdpr-cookie-notice
editor: typora
theme:
  - garth
  - pwa
  - netlify
logo: logo.png
image: logo.png
googleanalytics: UA-30599234-2
cloudflareinsights: aa58d54d00e04d9e8f0fc44730cafff7
manifest:
  background_color: '#F3F7FC'
  theme_color: '#CADCF2'
  theme_color_dark: '#000'
  icons:
    - logo-192.png
    - logo-512.png
    - logo-512.webp
  shortcuts: true
serviceworker:
  enabled: true
  debug: false
  precache:
    - logo-192.png
    - logo-512.png
    - logo-512.webp
  notification:
    enabled: false
metatags:
  jsonld:
    enabled: true
netlify:
  redirects:
    - from: https://arnaudligny.netlify.com/*
      to: https://arnaudligny.fr/:splat
      status: 301
      force: true
body:
  images:
    caption:
      enabled: true
    resize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
  highlight:
    enabled: true
  links:
    embed:
      enabled: true
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
      sizes:
        default: 100vw
        test: "(max-width: 800px) 768px, 1024px"
    webp:
      enabled: true
