title: Arnaud Ligny
baseline: Consultant technique Web, mobile & e-commerce
baseurl: https://arnaudligny.fr/
description: Arnaud Ligny, Consultant technique Web, mobile & e-commerce.
keywords:
 - Consultant technique
 - Web
 - Application Mobile
 - e-commerce
 - Magento
 - IoT
menus:
  main:
    - id: blog
      weight: 1
    - id: projets
      weight: 2
  footer:
    - id: a-propos
      name: À propos
      url: a-propos
author:
  firstname: Arnaud
  lastname: Ligny
  email: arnaud[AROBASE]ligny[POINT]fr
  username: Narno
  job: Consultant technique
  cv: CV_ArnaudLigny-2016.pdf
  statut: En poste
social:
  twitter: ArnaudLigny
  github: Narno
  linkedin: arnaudligny
  facebook_id: 516589570
language: fr
languages:
  - code: fr
    name: Français
    locale: fr_FR
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ''
  pagetypeformats:
    section: ['html', 'atom', 'rss', 'json']
defaultpages:
  sitemap:
    published: true
  404:
    published: true
virtualpages:
  - path: code
    redirect: https://github.com/Narno
  - path: blog/work-in-progress
    redirect: /
  - path: blog/v-rifier-la-validit-des-fichiers-de-configuration-xml-de-magento
    redirect: blog/verifier-la-validite-des-fichiers-de-configuration-xml-de-magento/
  - path: blog/t-l-charger-manuellement-une-extension-magento
    redirect: blog/telecharger-manuellement-une-extension-magento/
  - path: _redirects
    output: netlify_redirects
googleanalytics: UA-30599234-2
source: https://github.com/Narno/arnaudligny.fr/edit/master/content/
comments: false
static:
  exclude:
    - CV_ArnaudLigny-2014.pdf
    - CV_ArnaudLigny-2015.pdf
editor: typora
theme:
  - garth
  - serviceworker
logo: aligny.jpg
image: aligny.jpg
manifest:
  theme_color: '#CADCF2'
  icons:
    - src: icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: true
  debug: false
  precache:
    - aligny.jpg
    - styles.min.css
    - icon-512x512.png
  notification:
    enabled: true
    message: 'Nouvelle version'
cache:
  enabled: true
  dir: .cache #/opt/buildhome/cache
  external: false
