[build]
  command = "chmod +x netlify.sh && bash netlify.sh"
  publish = "_site"

[context.deploy-preview]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL && php phpoole.phar --version"

[context.branch-deploy]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"
