[build]
  command = "chmod +x scripts/netlify.sh && bash scripts/netlify.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2" }

[context.deploy-preview]
  command = "chmod +x scripts/netlify.sh && bash scripts/netlify.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x scripts/netlify.sh && bash scripts/netlify.sh $DEPLOY_PRIME_URL"

[context.wip]
  command = "chmod +x scripts/netlify-beta.sh && bash scripts/netlify-beta.sh $DEPLOY_PRIME_URL"
