[build]
  command = "chmod +x scripts/netlify.sh && bash scripts/netlify.sh"
  publish = "_site"

[context.deploy-preview]
  command = "chmod +x scripts/netlify.sh && bash scripts/netlify.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x scripts/netlify.sh && bash scripts/netlify.sh $DEPLOY_PRIME_URL"
