[build]
  publish = "_site"
  command = "chmod +x ./scripts/netlify.sh && bash ./scripts/netlify.sh"
[build.environment]
  PHP_VERSION = "7.2"
  CECIL_ENV = "production"
  CECIL_CACHE_DIR = "/opt/build/cache/"

[context.deploy-preview.environment]
  CECIL_ENV = "preview"

[context.branch-deploy.environment]
  CECIL_ENV = "branch"
