---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/tags
  label: Tags
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  new_doc_ext: md
- type: directory
  path: content/projets
  label: Projets
  create: documents
  match: "**/*"
  new_doc_ext: md
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: curl -SOL https://cecil.app/cecil.phar && php cecil.phar build
    -v --baseurl=$DEPLOY_URL
  publish_command: hugo -d public
  preview_env:
  - PHP_VERSION=7.2
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: _site
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: 0.55.6
