metatags:
  jsonld:
    enabled: false
pages:
  body:
    images:
      formats: []
      resize: false
      responsive: false
      caption: true
      placeholder:
assets:
  images:
    optimize: false
    responsive: false
    cdn: false
serviceworker:
  enabled: false
