serviceworker:
  enabled: false
metatags:
  jsonld:
    enabled: false
pages:
  body:
    images:
      resize:
        enabled: false
      responsive:
        enabled: false
      webp:
        enabled: false
      caption:
        enabled: true
      placeholder: 'lqip'
assets:
  images:
    optimize:
      enabled: false
    responsive:
      enabled: false
    webp:
      enabled: false
    cdn:
      enabled: false
