name: Integration tests

on:
  push:
    branches: [master]
    paths:
      - 'layouts/**'
      - 'assets/**'
  workflow_dispatch:

jobs:
  test-site:
    name: Site tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: pre-installed
          extensions: mbstring, fileinfo, gd, imagick, intl, gettext, :redis
      - name: Download Cecil
        run: curl -sSOL https://cecil.app/cecil.phar
      - name: Install theme(s)
        run: |
          if [[ -f "composer.json" ]]; then
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install --prefer-dist --no-dev --no-progress --ansi
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Restore Playwright binaries cache
        uses: actions/cache@v5
        id: playwright-cache
        with:
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.ts') }}
          path: ~/.cache/playwright
          restore-keys: |
            ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.ts') }}
            ${{ runner.os }}-playwright-
      - name: Install Playwright browsers
        env:
          CI: 1
        run: |
          npm ci
          npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run Playwright tests
        run: npm run test
      - name: Upload Playwright report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
